// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSJ5g6AECPvRGwgfvy2gb0t5-P06my18g',
    appId: '1:200067403106:web:bb7c28bec0fc513a64703b',
    messagingSenderId: '200067403106',
    projectId: 'firebase-shoppee',
    authDomain: 'fir-shoppee.firebaseapp.com',
    storageBucket: 'firebase-shoppee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUmh1ONP4oT4TOK_01fM8dOe1_BopyWbI',
    appId: '1:200067403106:android:97fb61151e2cdd5764703b',
    messagingSenderId: '200067403106',
    projectId: 'firebase-shoppee',
    storageBucket: 'firebase-shoppee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwSL7xTxyWC9N-I52tFPYo3byqNpZJRM4',
    appId: '1:200067403106:ios:1927b548c2c675e264703b',
    messagingSenderId: '200067403106',
    projectId: 'firebase-shoppee',
    storageBucket: 'firebase-shoppee.appspot.com',
    iosClientId: '200067403106-kgs2kj5k672p3mgl021a54a6lv2b4snh.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppee',
  );
}
